def kavdi_map(karu,kalam_num,num):
        if karu=='p41' or karu=='p42' or karu=='p43' or karu=='p44':
            if kalam_num==29:
                if num==1:
                    return 23
                elif num==2:
                    return 29
                elif num==3:
                    return 29
                elif num==4:
                    return 23
                
            elif kalam_num==23:
                if num==1:
                    return 24
                elif num==2:
                    return 25
                elif num==3:
                    return 20
                elif num==4:
                    return 15
            
            elif kalam_num==24:
                if num==1:
                    return 25
                elif num==2:
                    return 20
                elif num==3:
                    return 15
                elif num==4:
                    return 10
            elif kalam_num==25:
                if num==1:
                    return 20
                elif num==2:
                    return 15
                elif num==3:
                    return 10
                elif num==4:
                    return 5
                
                
            elif kalam_num==20:
                if num==1:
                    return 15
                elif num==2:
                    return 10
                elif num==3:
                    return 5
                elif num==4:
                    return 4
            
            elif kalam_num==15:
                if num==1:
                    return 10
                elif num==2:
                    return 5
                elif num==3:
                    return 4
                elif num==4:
                    return 3
            elif kalam_num==10:
                if num==1:
                    return 5
                elif num==2:
                    return 4
                elif num==3:
                    return 3
                elif num==4:
                    return 2
                
            elif kalam_num==5:
                if num==1:
                    return 4
                elif num==2:
                    return 3
                elif num==3:
                    return 2
                elif num==4:
                    return 1
            
            elif kalam_num==4:
                if num==1:
                    return 3
                elif num==2:
                    return 2
                elif num==3:
                    return 1
                elif num==4:
                    return 6
            elif kalam_num==3:
                if num==1:
                    return 2
                elif num==2:
                    return 1
                elif num==3:
                    return 6
                elif num==4:
                    return 11
                
            elif kalam_num==2:
                if num==1:
                    return 1
                elif num==2:
                    return 6
                elif num==3:
                    return 11
                elif num==4:
                    return 16
            elif kalam_num==1:
                if num==1:
                    return 6
                elif num==2:
                    return 11
                elif num==3:
                    return 16
                elif num==4:
                    return 21
                    
##{29-1 completed}
                
            elif kalam_num==6:
                if num==1:
                    return 11
                elif num==2:
                    return 16
                elif num==3:
                    return 21
                elif num==4:
                    return 22
            
            elif kalam_num==11:
                if num==1:
                    return 16
                elif num==2:
                    return 21
                elif num==3:
                    return 22
                elif num==4:
                    return 17
            elif kalam_num==16:
                if num==1:
                    return 21
                elif num==2:
                    return 22
                elif num==3:
                    return 17
                elif num==4:
                    return 12
            elif kalam_num==21:
                if num==1:
                    return 22
                elif num==2:
                    return 17
                elif num==3:
                    return 12
                elif num==4:
                    return 7
                
                
            elif kalam_num==22:
                if num==1:
                    return 17
                elif num==2:
                    return 12
                elif num==3:
                    return 7
                elif num==4:
                    return 8
            
            elif kalam_num==17:
                if num==1:
                    return 12
                elif num==2:
                    return 7
                elif num==3:
                    return 8
                elif num==4:
                    return 9
            elif kalam_num==12:
                if num==1:
                    return 7
                elif num==2:
                    return 8
                elif num==3:
                    return 9
                elif num==4:
                    return 14
                
            elif kalam_num==7:
                if num==1:
                    return 8
                elif num==2:
                    return 9
                elif num==3:
                    return 14
                elif num==4:
                    return 19
            
            elif kalam_num==8:
                if num==1:
                    return 9
                elif num==2:
                    return 14
                elif num==3:
                    return 19
                elif num==4:
                    return 18
            elif kalam_num==9:
                if num==1:
                    return 14
                elif num==2:
                    return 19
                elif num==3:
                    return 18
                elif num==4:
                    return 13
                
            elif kalam_num==14:
                if num==1:
                    return 19
                elif num==2:
                    return 18
                elif num==3:
                    return 13
                elif num==4:
                    return 14
            elif kalam_num==19:
                if num==1:
                    return 18
                elif num==2:
                    return 13
                elif num==3:
                    return 19
                elif num==4:
                    return 19
            elif kalam_num==18:
                if num==1:
                    return 13
                elif num==2:
                    return 18
                elif num==3:
                    return 18
                elif num==4:
                    return 18
                
                
##next p1
                
                
        if karu=='p11' or karu=='p12' or karu=='p13' or karu=='p14':
            if kalam_num==26:
                if num==1:
                    return 3
                elif num==2:
                    return 26
                elif num==3:
                    return 26
                elif num==4:
                    return 3
                
            elif kalam_num==3:
                if num==1:
                    return 2
                elif num==2:
                    return 1
                elif num==3:
                    return 6
                elif num==4:
                    return 11
            
            elif kalam_num==2:
                if num==1:
                    return 1
                elif num==2:
                    return 6
                elif num==3:
                    return 11
                elif num==4:
                    return 16
            elif kalam_num==1:
                if num==1:
                    return 6
                elif num==2:
                    return 11
                elif num==3:
                    return 16
                elif num==4:
                    return 21
                
                
            elif kalam_num==6:
                if num==1:
                    return 11
                elif num==2:
                    return 16
                elif num==3:
                    return 21
                elif num==4:
                    return 22
            
            elif kalam_num==11:
                if num==1:
                    return 16
                elif num==2:
                    return 21
                elif num==3:
                    return 22
                elif num==4:
                    return 23
            elif kalam_num==16:
                if num==1:
                    return 21
                elif num==2:
                    return 22
                elif num==3:
                    return 23
                elif num==4:
                    return 24
                
            elif kalam_num==21:
                if num==1:
                    return 22
                elif num==2:
                    return 23
                elif num==3:
                    return 24
                elif num==4:
                    return 25
            
            elif kalam_num==22:
                if num==1:
                    return 23
                elif num==2:
                    return 24
                elif num==3:
                    return 25
                elif num==4:
                    return 20
            elif kalam_num==23:
                if num==1:
                    return 24
                elif num==2:
                    return 25
                elif num==3:
                    return 20
                elif num==4:
                    return 15
                
            elif kalam_num==24:
                if num==1:
                    return 25
                elif num==2:
                    return 20
                elif num==3:
                    return 15
                elif num==4:
                    return 10
            elif kalam_num==25:
                if num==1:
                    return 20
                elif num==2:
                    return 15
                elif num==3:
                    return 10
                elif num==4:
                    return 5
                    
##{26-25 completed}
                
            elif kalam_num==20:
                if num==1:
                    return 15
                elif num==2:
                    return 10
                elif num==3:
                    return 5
                elif num==4:
                    return 4
            
            elif kalam_num==15:
                if num==1:
                    return 10
                elif num==2:
                    return 5
                elif num==3:
                    return 4
                elif num==4:
                    return 9
            elif kalam_num==10:
                if num==1:
                    return 5
                elif num==2:
                    return 4
                elif num==3:
                    return 9
                elif num==4:
                    return 14
            elif kalam_num==5:
                if num==1:
                    return 4
                elif num==2:
                    return 9
                elif num==3:
                    return 14
                elif num==4:
                    return 19
                
                
            elif kalam_num==4:
                if num==1:
                    return 9
                elif num==2:
                    return 14
                elif num==3:
                    return 19
                elif num==4:
                    return 18
            
            elif kalam_num==9:
                if num==1:
                    return 14
                elif num==2:
                    return 19
                elif num==3:
                    return 18
                elif num==4:
                    return 17
            elif kalam_num==14:
                if num==1:
                    return 19
                elif num==2:
                    return 18
                elif num==3:
                    return 17
                elif num==4:
                    return 12
                
            elif kalam_num==19:
                if num==1:
                    return 18
                elif num==2:
                    return 17
                elif num==3:
                    return 12
                elif num==4:
                    return 7
            
            elif kalam_num==18:
                if num==1:
                    return 17
                elif num==2:
                    return 12
                elif num==3:
                    return 7
                elif num==4:
                    return 8
            elif kalam_num==17:
                if num==1:
                    return 12
                elif num==2:
                    return 7
                elif num==3:
                    return 8
                elif num==4:
                    return 13
                
            elif kalam_num==12:
                if num==1:
                    return 7
                elif num==2:
                    return 8
                elif num==3:
                    return 13
                elif num==4:
                    return 12
            elif kalam_num==7:
                if num==1:
                    return 8
                elif num==2:
                    return 13
                elif num==3:
                    return 7
                elif num==4:
                    return 7
            elif kalam_num==8:
                if num==1:
                    return 13
                elif num==2:
                    return 8
                elif num==3:
                    return 8
                elif num==4:
                    return 8
                
                
        if karu=='p21' or karu=='p22' or karu=='p23' or karu=='p24':
            if kalam_num==27:
                if num==1:
                    return 11
                elif num==2:
                    return 27
                elif num==3:
                    return 27
                elif num==4:
                    return 11
                
            elif kalam_num==11:
                if num==1:
                    return 16
                elif num==2:
                    return 21
                elif num==3:
                    return 22
                elif num==4:
                    return 23
            
            elif kalam_num==16:
                if num==1:
                    return 21
                elif num==2:
                    return 22
                elif num==3:
                    return 23
                elif num==4:
                    return 24
            elif kalam_num==21:
                if num==1:
                    return 22
                elif num==2:
                    return 23
                elif num==3:
                    return 24
                elif num==4:
                    return 25
                
                
            elif kalam_num==22:
                if num==1:
                    return 23
                elif num==2:
                    return 24
                elif num==3:
                    return 25
                elif num==4:
                    return 20
            
            elif kalam_num==23:
                if num==1:
                    return 24
                elif num==2:
                    return 25
                elif num==3:
                    return 20
                elif num==4:
                    return 15
            elif kalam_num==24:
                if num==1:
                    return 25
                elif num==2:
                    return 20
                elif num==3:
                    return 15
                elif num==4:
                    return 10
                
            elif kalam_num==25:
                if num==1:
                    return 20
                elif num==2:
                    return 15
                elif num==3:
                    return 10
                elif num==4:
                    return 5
            
            elif kalam_num==20:
                if num==1:
                    return 15
                elif num==2:
                    return 10
                elif num==3:
                    return 5
                elif num==4:
                    return 4
            elif kalam_num==15:
                if num==1:
                    return 10
                elif num==2:
                    return 5
                elif num==3:
                    return 4
                elif num==4:
                    return 3
                
            elif kalam_num==10:
                if num==1:
                    return 5
                elif num==2:
                    return 4
                elif num==3:
                    return 3
                elif num==4:
                    return 2
            elif kalam_num==5:
                if num==1:
                    return 4
                elif num==2:
                    return 3
                elif num==3:
                    return 2
                elif num==4:
                    return 1
                    
##{27-5 completed}
                
            elif kalam_num==4:
                if num==1:
                    return 3
                elif num==2:
                    return 2
                elif num==3:
                    return 1
                elif num==4:
                    return 6
            
            elif kalam_num==3:
                if num==1:
                    return 2
                elif num==2:
                    return 1
                elif num==3:
                    return 6
                elif num==4:
                    return 7
            elif kalam_num==2:
                if num==1:
                    return 1
                elif num==2:
                    return 6
                elif num==3:
                    return 7
                elif num==4:
                    return 8
            elif kalam_num==1:
                if num==1:
                    return 6
                elif num==2:
                    return 7
                elif num==3:
                    return 8
                elif num==4:
                    return 9
                
                
            elif kalam_num==6:
                if num==1:
                    return 7
                elif num==2:
                    return 8
                elif num==3:
                    return 9
                elif num==4:
                    return 14
            
            elif kalam_num==7:
                if num==1:
                    return 8
                elif num==2:
                    return 9
                elif num==3:
                    return 14
                elif num==4:
                    return 19
            elif kalam_num==8:
                if num==1:
                    return 9
                elif num==2:
                    return 14
                elif num==3:
                    return 19
                elif num==4:
                    return 18
                
            elif kalam_num==9:
                if num==1:
                    return 14
                elif num==2:
                    return 19
                elif num==3:
                    return 18
                elif num==4:
                    return 17
            
            elif kalam_num==14:
                if num==1:
                    return 19
                elif num==2:
                    return 18
                elif num==3:
                    return 17
                elif num==4:
                    return 12
            elif kalam_num==19:
                if num==1:
                    return 18
                elif num==2:
                    return 17
                elif num==3:
                    return 12
                elif num==4:
                    return 13
                
            elif kalam_num==18:
                if num==1:
                    return 17
                elif num==2:
                    return 12
                elif num==3:
                    return 13
                elif num==4:
                    return 18
            elif kalam_num==17:
                if num==1:
                    return 12
                elif num==2:
                    return 13
                elif num==3:
                    return 17
                elif num==4:
                    return 17
            elif kalam_num==12:
                if num==1:
                    return 13
                elif num==2:
                    return 12
                elif num==3:
                    return 12
                elif num==4:
                    return 12
        if karu=='p31' or karu=='p32' or karu=='p33' or karu=='p34':
            if kalam_num==28:
                if num==1:
                    return 15
                elif num==2:
                    return 28
                elif num==3:
                    return 28
                elif num==4:
                    return 15
                
            elif kalam_num==15:
                if num==1:
                    return 10
                elif num==2:
                    return 5
                elif num==3:
                    return 4
                elif num==4:
                    return 3
            
            elif kalam_num==10:
                if num==1:
                    return 5
                elif num==2:
                    return 4
                elif num==3:
                    return 3
                elif num==4:
                    return 2
            elif kalam_num==5:
                if num==1:
                    return 4
                elif num==2:
                    return 3
                elif num==3:
                    return 2
                elif num==4:
                    return 1
                
                
            elif kalam_num==4:
                if num==1:
                    return 3
                elif num==2:
                    return 2
                elif num==3:
                    return 1
                elif num==4:
                    return 6
            
            elif kalam_num==3:
                if num==1:
                    return 2
                elif num==2:
                    return 1
                elif num==3:
                    return 6
                elif num==4:
                    return 11
            elif kalam_num==2:
                if num==1:
                    return 1
                elif num==2:
                    return 6
                elif num==3:
                    return 11
                elif num==4:
                    return 16
                
            elif kalam_num==1:
                if num==1:
                    return 6
                elif num==2:
                    return 11
                elif num==3:
                    return 16
                elif num==4:
                    return 21
            
            elif kalam_num==6:
                if num==1:
                    return 11
                elif num==2:
                    return 16
                elif num==3:
                    return 21
                elif num==4:
                    return 22
            elif kalam_num==11:
                if num==1:
                    return 16
                elif num==2:
                    return 21
                elif num==3:
                    return 22
                elif num==4:
                    return 23
                
            elif kalam_num==16:
                if num==1:
                    return 21
                elif num==2:
                    return 22
                elif num==3:
                    return 23
                elif num==4:
                    return 24
            elif kalam_num==21:
                if num==1:
                    return 22
                elif num==2:
                    return 23
                elif num==3:
                    return 24
                elif num==4:
                    return 25
                    
##{28-25 completed}
                
            elif kalam_num==22:
                if num==1:
                    return 23
                elif num==2:
                    return 24
                elif num==3:
                    return 25
                elif num==4:
                    return 20
            
            elif kalam_num==23:
                if num==1:
                    return 24
                elif num==2:
                    return 25
                elif num==3:
                    return 20
                elif num==4:
                    return 19
            elif kalam_num==24:
                if num==1:
                    return 25
                elif num==2:
                    return 20
                elif num==3:
                    return 19
                elif num==4:
                    return 18
            elif kalam_num==25:
                if num==1:
                    return 20
                elif num==2:
                    return 19
                elif num==3:
                    return 18
                elif num==4:
                    return 17
                
                
            elif kalam_num==20:
                if num==1:
                    return 19
                elif num==2:
                    return 18
                elif num==3:
                    return 17
                elif num==4:
                    return 12
            
            elif kalam_num==19:
                if num==1:
                    return 18
                elif num==2:
                    return 17
                elif num==3:
                    return 12
                elif num==4:
                    return 7
            elif kalam_num==18:
                if num==1:
                    return 17
                elif num==2:
                    return 12
                elif num==3:
                    return 7
                elif num==4:
                    return 8
                
            elif kalam_num==17:
                if num==1:
                    return 12
                elif num==2:
                    return 7
                elif num==3:
                    return 8
                elif num==4:
                    return 9
            
            elif kalam_num==12:
                if num==1:
                    return 7
                elif num==2:
                    return 8
                elif num==3:
                    return 9
                elif num==4:
                    return 14
            elif kalam_num==7:
                if num==1:
                    return 8
                elif num==2:
                    return 9
                elif num==3:
                    return 14
                elif num==4:
                    return 13
                
            elif kalam_num==8:
                if num==1:
                    return 9
                elif num==2:
                    return 14
                elif num==3:
                    return 13
                elif num==4:
                    return 8
            elif kalam_num==9:
                if num==1:
                    return 14
                elif num==2:
                    return 13
                elif num==3:
                    return 9
                elif num==4:
                    return 9
            elif kalam_num==14:
                if num==1:
                    return 13
                elif num==2:
                    return 14
                elif num==3:
                    return 14
                elif num==4:
                    return 14
                    